// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_dtametaTMB_TMBExports
#include <TMB.hpp>
#include "Hoyer.hpp"
#include "RutterGatsonis.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "Hoyer") {
    return Hoyer(this);
  } else if(model == "RutterGatsonis") {
    return RutterGatsonis(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
